-- Wolfari PostgreSQL 16+ | fresh installation only. Run as DBA outside a transaction.
-- Set passwords securely with psql \password; do not commit secrets.
CREATE ROLE identity_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE identity_db OWNER identity_app;
REVOKE ALL ON DATABASE identity_db FROM PUBLIC;
GRANT CONNECT ON DATABASE identity_db TO identity_app;
CREATE ROLE trip_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE trip_db OWNER trip_app;
REVOKE ALL ON DATABASE trip_db FROM PUBLIC;
GRANT CONNECT ON DATABASE trip_db TO trip_app;
CREATE ROLE travel_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE travel_db OWNER travel_app;
REVOKE ALL ON DATABASE travel_db FROM PUBLIC;
GRANT CONNECT ON DATABASE travel_db TO travel_app;
CREATE ROLE finance_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE finance_db OWNER finance_app;
REVOKE ALL ON DATABASE finance_db FROM PUBLIC;
GRANT CONNECT ON DATABASE finance_db TO finance_app;
CREATE ROLE automation_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE automation_db OWNER automation_app;
REVOKE ALL ON DATABASE automation_db FROM PUBLIC;
GRANT CONNECT ON DATABASE automation_db TO automation_app;
